name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: "5.3.0"
          dune-cache: true
      - run: opam install . --deps-only --with-test -y
      - run: dune runtest
